-- WanderSafe D1 Database Schema
-- Cloudflare D1 (SQLite-compatible)
-- Version: 1.1.0
--
-- This schema supports the WanderSafe LGBTQ+ travel safety intelligence platform.
-- All alert records start with human_reviewed = 0 (false). Nothing is surfaced
-- to the public platform until a trained human reviewer sets human_reviewed = 1
-- and published_at is populated.
--
-- Run: wrangler d1 execute wandersafe --file=schema/d1-schema.sql

PRAGMA foreign_keys = ON;

-- ============================================================
-- destinations
-- Master list of monitored locations.
-- safety_tier: 1 (generally safe) through 4 (do not travel)
-- ============================================================
CREATE TABLE IF NOT EXISTS destinations (
  id             TEXT PRIMARY KEY,          -- ISO 3166-1 alpha-2 for countries (e.g., 'ES'),
                                            -- or country+city slug for cities (e.g., 'ES-barcelona')
  country_code   TEXT NOT NULL,             -- ISO 3166-1 alpha-2 (e.g., 'ES')
  country_name   TEXT NOT NULL,             -- full English name (e.g., 'Spain')
  city           TEXT,                      -- null for country-level records
  region         TEXT,                      -- state/province/region if applicable
  safety_tier    INTEGER NOT NULL DEFAULT 2 -- 1=generally safe, 2=exercise caution,
                                            -- 3=high risk, 4=do not travel
    CHECK (safety_tier BETWEEN 1 AND 4),
  last_updated   TEXT NOT NULL DEFAULT (datetime('now')),
  notes          TEXT                       -- internal reviewer notes (never published)
);

CREATE INDEX IF NOT EXISTS idx_destinations_country ON destinations(country_code);

-- ============================================================
-- legal_status
-- LGBTQ+-specific legal status per destination.
-- Updated by legal-monitor agent from Equaldex API.
-- Values use Equaldex terminology where possible.
-- ============================================================
CREATE TABLE IF NOT EXISTS legal_status (
  id                      INTEGER PRIMARY KEY AUTOINCREMENT,
  destination_id          TEXT NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  same_sex_legal          TEXT,             -- 'legal', 'illegal', 'no_laws', 'varies'
  marriage_equality       TEXT,             -- 'legal', 'civil_union', 'none'
  adoption_rights         TEXT,             -- 'legal', 'single_only', 'none'
  anti_discrimination     TEXT,             -- 'sexual_orientation', 'gender_identity', 'both', 'none'
  anti_propaganda_law     INTEGER DEFAULT 0 -- 1 if anti-propaganda law exists
    CHECK (anti_propaganda_law IN (0, 1)),
  criminalization         TEXT,             -- 'death_penalty', 'imprisonment', 'fine', 'none'
  gender_marker_change    TEXT,             -- 'legal', 'surgery_required', 'impossible'
  conversion_therapy      TEXT,             -- 'banned', 'legal', 'no_law'
  last_equaldex_update    TEXT,             -- ISO 8601 datetime of last Equaldex sync
  equaldex_region_id      TEXT,             -- Equaldex internal ID for change tracking
  created_at              TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_legal_status_destination ON legal_status(destination_id);

-- ============================================================
-- safety_alerts
-- Generated by monitoring agents. All start human_reviewed = 0.
-- published_at is set by human reviewer on approval.
-- ============================================================
CREATE TABLE IF NOT EXISTS safety_alerts (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  destination_id  TEXT NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  severity        TEXT NOT NULL
    CHECK (severity IN ('informational', 'low', 'medium', 'high', 'critical')),
  agent_type      TEXT NOT NULL
    CHECK (agent_type IN ('legal', 'news', 'event', 'community', 'social')),
  source_url      TEXT,                     -- canonical URL of the triggering source
  source_name     TEXT,                     -- human-readable source name
  summary         TEXT NOT NULL,            -- plain-language description of the alert
  previous_value  TEXT,                     -- what was true before (for legal changes)
  new_value       TEXT,                     -- what is true now (for legal changes)
  human_reviewed  INTEGER NOT NULL DEFAULT 0
    CHECK (human_reviewed IN (0, 1)),
  reviewer_notes  TEXT,                     -- internal notes from human reviewer (never published)
  published_at    TEXT,                     -- null until human approved; ISO 8601 when published
  expires_at      TEXT,                     -- optional: when this alert should auto-expire
  raw_payload     TEXT,                     -- JSON: full source API response for audit trail
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_alerts_destination ON safety_alerts(destination_id);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON safety_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_reviewed ON safety_alerts(human_reviewed);
CREATE INDEX IF NOT EXISTS idx_alerts_published ON safety_alerts(published_at);
CREATE INDEX IF NOT EXISTS idx_alerts_agent ON safety_alerts(agent_type);

-- ============================================================
-- community_reports
-- Submitted by travelers via Tally form → webhook → D1.
-- No Google Sheets. Tally sends a signed webhook POST to the
-- community-validator Worker, which validates the HMAC,
-- classifies with Claude, strips PII, and inserts here.
-- human_reviewed = 0 and approved = 0 until reviewer signs off.
-- published_at is set by reviewer on approval.
-- ============================================================
CREATE TABLE IF NOT EXISTS community_reports (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  -- Destination fields: destination_id is nullable until a human reviewer
  -- resolves the free-text destination to a canonical destination record
  destination_id        TEXT REFERENCES destinations(id) ON DELETE SET NULL,
  destination_raw       TEXT,                     -- free-text destination from Tally form
  destination_normalized TEXT,                    -- AI-resolved: "City, Country"
  country_code          TEXT,                     -- ISO 3166-1 alpha-2 (AI-resolved)
  -- Report metadata
  tally_response_id     TEXT UNIQUE,              -- Tally responseId for idempotency
  submitted_at          TEXT,                     -- ISO 8601 from Tally payload
  visit_date            TEXT,                     -- traveler-reported travel date (YYYY-MM or YYYY-MM-DD)
  -- Classification (by community-validator agent via Claude)
  audience_tags         TEXT,                     -- JSON array: ['gay_men','trans','solo_traveler', ...]
  incident_type         TEXT
    CHECK (incident_type IN (
      'none',
      'verbal_harassment',
      'physical_threat',
      'physical_assault',
      'police_interaction',
      'property_crime',
      'discrimination',
      'positive_experience',
      'other'
    )),
  severity              TEXT
    CHECK (severity IN ('informational', 'low', 'medium', 'high', 'critical')),
  validity_score        REAL,                     -- 0.0–1.0 assigned by agent
  summary               TEXT,                     -- agent-generated plain-language summary (no PII)
  description_sanitized TEXT,                     -- PII-stripped free-text description from form
  neighborhood          TEXT,                     -- general area within city (never specific address)
  classifier_error      TEXT,                     -- if Claude classification failed, error message
  -- Review workflow
  human_reviewed        INTEGER NOT NULL DEFAULT 0
    CHECK (human_reviewed IN (0, 1)),             -- 1 once reviewer acts (approve OR reject)
  approved              INTEGER NOT NULL DEFAULT 0
    CHECK (approved IN (0, 1)),
  reviewer_notes        TEXT,                     -- internal notes from human reviewer
  published_at          TEXT,                     -- null until approved; ISO 8601 when published
  created_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_reports_destination ON community_reports(destination_id);
CREATE INDEX IF NOT EXISTS idx_reports_approved ON community_reports(approved);
CREATE INDEX IF NOT EXISTS idx_reports_incident ON community_reports(incident_type);

-- ============================================================
-- subscribers
-- Alert subscribers. Stores preferences for destination-specific
-- or tier-based alerts. Email is stored hashed for lookup;
-- plaintext email is never stored after the welcome email is sent.
--
-- alert_tier: 'all' = every alert; 'high' = high+critical only;
--             'critical' = critical only
-- ============================================================
CREATE TABLE IF NOT EXISTS subscribers (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  email_hash       TEXT NOT NULL UNIQUE,    -- SHA-256 of lowercase email — for dedup only
  destination_tags TEXT,                    -- JSON array of destination IDs to monitor
  alert_tier       TEXT NOT NULL DEFAULT 'high'
    CHECK (alert_tier IN ('all', 'high', 'critical')),
  buttondown_id    TEXT,                    -- Buttondown subscriber ID for email delivery
  created_at       TEXT NOT NULL DEFAULT (datetime('now')),
  last_active      TEXT
);

CREATE INDEX IF NOT EXISTS idx_subscribers_tier ON subscribers(alert_tier);

-- ============================================================
-- agent_runs
-- Audit log of every agent execution. Used for debugging,
-- monitoring agent health, and proving to funders that the
-- pipeline runs as described.
-- ============================================================
CREATE TABLE IF NOT EXISTS agent_runs (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  agent_type    TEXT NOT NULL,
  started_at    TEXT NOT NULL DEFAULT (datetime('now')),
  finished_at   TEXT,
  status        TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'success', 'error')),
  alerts_created INTEGER DEFAULT 0,
  error_message  TEXT,
  metadata       TEXT                       -- JSON: agent-specific run metadata
);

CREATE INDEX IF NOT EXISTS idx_runs_agent ON agent_runs(agent_type);
CREATE INDEX IF NOT EXISTS idx_runs_status ON agent_runs(status);

-- ============================================================
-- destination_scores
-- Computed safety scores from the scoring pipeline.
-- Updated by scoring Worker whenever an alert is approved.
-- This is what destination pages actually display.
-- ============================================================
CREATE TABLE IF NOT EXISTS destination_scores (
  id                   INTEGER PRIMARY KEY AUTOINCREMENT,
  destination_id       TEXT NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  score                REAL NOT NULL,           -- 0–100 numeric score
  tier                 INTEGER NOT NULL          -- 1=safe, 2=caution, 3=high_risk, 4=do_not_travel
    CHECK (tier BETWEEN 1 AND 4),
  tier_label           TEXT NOT NULL,            -- 'Safe', 'Exercise Caution', 'High Risk', 'Do Not Travel'
  confidence           TEXT NOT NULL DEFAULT 'medium'
    CHECK (confidence IN ('high', 'medium', 'low', 'insufficient')),
  state_erasure_score  REAL,                     -- sub-score: state criminalization axis
  digital_exploit_score REAL,                    -- sub-score: digital exploitation axis
  vigilante_score      REAL,                     -- sub-score: vigilante enforcement axis
  community_delta      REAL DEFAULT 0,           -- community report adjustment (-15 to +15)
  scoring_version      TEXT NOT NULL DEFAULT '1.0',
  scored_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_scores_destination ON destination_scores(destination_id);

-- ============================================================
-- legiscan_bills
-- US state + federal LGBTQ+-relevant legislation.
-- Populated by legiscan-monitor Worker.
-- ============================================================
CREATE TABLE IF NOT EXISTS legiscan_bills (
  id                      INTEGER PRIMARY KEY AUTOINCREMENT,
  legiscan_bill_id        INTEGER NOT NULL UNIQUE,
  state                   TEXT NOT NULL,          -- 2-letter state code or 'US' for federal
  bill_number             TEXT NOT NULL,          -- e.g., 'HB 1234'
  title                   TEXT NOT NULL,
  description             TEXT,
  status                  TEXT NOT NULL,          -- 'introduced', 'committee', 'passed', 'enacted', 'failed', 'vetoed'
  introduced_date         TEXT,
  last_action             TEXT,
  last_action_date        TEXT,
  lgbtq_relevance_score   REAL NOT NULL,          -- 0.0–1.0 from Claude Haiku classifier
  lgbtq_relevance_summary TEXT,                   -- classifier's explanation
  threat_type             TEXT,                   -- 'criminalization', 'trans_healthcare', 'anti_drag',
                                                  -- 'gender_recognition', 'hiv_criminalization',
                                                  -- 'public_accommodation', 'education', 'other'
  affected_destinations   TEXT,                   -- JSON array of destination_ids affected
  legiscan_change_hash    TEXT,                   -- for delta detection (only re-fetch on hash change)
  bill_url                TEXT,
  created_at              TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_bills_state ON legiscan_bills(state);
CREATE INDEX IF NOT EXISTS idx_bills_status ON legiscan_bills(status);
CREATE INDEX IF NOT EXISTS idx_bills_relevance ON legiscan_bills(lgbtq_relevance_score);
CREATE INDEX IF NOT EXISTS idx_bills_threat ON legiscan_bills(threat_type);

-- ============================================================
-- scholar_reports
-- Post-trip safety reports from WWP scholars.
-- Separate from community_reports to allow Scholar badge
-- and to track which scholarship cohort each report belongs to.
-- Feeds into community_reports display layer after approval.
-- ============================================================
CREATE TABLE IF NOT EXISTS scholar_reports (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  destination_id    TEXT NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  scholar_cohort    TEXT NOT NULL,               -- e.g., '2024', '2025-spring'
  visit_date        TEXT,                        -- YYYY-MM of actual travel
  legal_assessment  TEXT,                        -- scholar's on-the-ground legal observation
  social_assessment TEXT,                        -- social atmosphere assessment
  safety_rating     INTEGER                      -- 1–5 self-reported
    CHECK (safety_rating BETWEEN 1 AND 5),
  incident_detail   TEXT,                        -- any incident or observation
  neighborhood      TEXT,
  tips              TEXT,                        -- practical advice for future travelers
  would_return      TEXT
    CHECK (would_return IN ('yes', 'yes_with_caution', 'no', 'unsure')),
  credit_preference TEXT NOT NULL DEFAULT 'scholar_anonymous'
    CHECK (credit_preference IN (
      'full_name', 'first_name_city', 'handle', 'scholar_anonymous'
    )),
  display_name      TEXT,                        -- populated if credit_preference != scholar_anonymous
  approved          INTEGER NOT NULL DEFAULT 0
    CHECK (approved IN (0, 1)),
  published_at      TEXT,
  community_report_id INTEGER REFERENCES community_reports(id), -- link when published to main feed
  created_at        TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_scholar_reports_destination ON scholar_reports(destination_id);
CREATE INDEX IF NOT EXISTS idx_scholar_reports_cohort ON scholar_reports(scholar_cohort);

-- ============================================================
-- access_grants
-- CiviCRM-driven access mapping.
-- Managed by civicrm-sync Worker.
-- ============================================================
CREATE TABLE IF NOT EXISTS access_grants (
  id                   INTEGER PRIMARY KEY AUTOINCREMENT,
  civicrm_contact_id   TEXT NOT NULL,
  buttondown_id        TEXT,                     -- Buttondown subscriber ID
  tier                 TEXT NOT NULL
    CHECK (tier IN ('scholar', 'alumni', 'board', 'advisor', 'donor', 'ambassador', 'partner')),
  destination_tags     TEXT,                     -- JSON array: specific destination tags applied
  granted_at           TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at           TEXT,                     -- NULL = permanent (alumni, board)
  revoked_at           TEXT,
  notes                TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_access_civicrm ON access_grants(civicrm_contact_id);
CREATE INDEX IF NOT EXISTS idx_access_tier ON access_grants(tier);

-- ============================================================
-- b2b_clients  [POST-FUNDING]
-- API key → client mapping for B2B tier.
-- ============================================================
CREATE TABLE IF NOT EXISTS b2b_clients (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  client_name     TEXT NOT NULL,
  api_key_hash    TEXT NOT NULL UNIQUE,          -- SHA-256 of API key (key itself never stored)
  tier            TEXT NOT NULL DEFAULT 'basic'
    CHECK (tier IN ('basic', 'standard', 'enterprise')),
  rate_limit      INTEGER NOT NULL DEFAULT 1000, -- requests per day
  allowed_fields  TEXT,                          -- JSON array of fields they can access
  contract_start  TEXT,
  contract_end    TEXT,
  monthly_fee_usd REAL,
  notes           TEXT,
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  last_active     TEXT
);

-- ============================================================
-- circles_contacts  [POST-FUNDING]
-- In-country contact directory for Circles feature.
-- Private keys never stored here — only public keys.
-- ============================================================
CREATE TABLE IF NOT EXISTS circles_contacts (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  subscriber_id     INTEGER NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
  destination_id    TEXT NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  availability      TEXT NOT NULL
    CHECK (availability IN ('emergency_only', 'open_to_connect')),
  public_key        TEXT NOT NULL,               -- E2E encryption public key
  bio               TEXT,                        -- 2-3 sentence optional bio
  languages         TEXT,                        -- JSON array
  verified_at       TEXT,                        -- when WanderSafe verified identity
  active            INTEGER NOT NULL DEFAULT 1
    CHECK (active IN (0, 1)),
  created_at        TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_circles_destination ON circles_contacts(destination_id);
CREATE INDEX IF NOT EXISTS idx_circles_availability ON circles_contacts(availability);
