-- WanderSafe D1 Database Schema
-- Cloudflare D1 (SQLite-compatible)
-- Version: 1.0.0
--
-- This schema supports the WanderSafe LGBTQ+ travel safety intelligence platform.
-- All alert records start with human_reviewed = 0 (false). Nothing is surfaced
-- to the public platform until a trained human reviewer sets human_reviewed = 1
-- and published_at is populated.
--
-- Run: wrangler d1 execute wandersafe --file=schema/d1-schema.sql

PRAGMA foreign_keys = ON;

-- ============================================================
-- destinations
-- Master list of monitored locations.
-- safety_tier: 1 (generally safe) through 4 (do not travel)
-- ============================================================
CREATE TABLE IF NOT EXISTS destinations (
  id             TEXT PRIMARY KEY,          -- ISO 3166-1 alpha-2 for countries (e.g., 'ES'),
                                            -- or country+city slug for cities (e.g., 'ES-barcelona')
  country_code   TEXT NOT NULL,             -- ISO 3166-1 alpha-2 (e.g., 'ES')
  country_name   TEXT NOT NULL,             -- full English name (e.g., 'Spain')
  city           TEXT,                      -- null for country-level records
  region         TEXT,                      -- state/province/region if applicable
  safety_tier    INTEGER NOT NULL DEFAULT 2 -- 1=generally safe, 2=exercise caution,
                                            -- 3=high risk, 4=do not travel
    CHECK (safety_tier BETWEEN 1 AND 4),
  last_updated   TEXT NOT NULL DEFAULT (datetime('now')),
  notes          TEXT                       -- internal reviewer notes (never published)
);

CREATE INDEX IF NOT EXISTS idx_destinations_country ON destinations(country_code);

-- ============================================================
-- legal_status
-- LGBTQ+-specific legal status per destination.
-- Updated by legal-monitor agent from Equaldex API.
-- Values use Equaldex terminology where possible.
-- ============================================================
CREATE TABLE IF NOT EXISTS legal_status (
  id                      INTEGER PRIMARY KEY AUTOINCREMENT,
  destination_id          TEXT NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  same_sex_legal          TEXT,             -- 'legal', 'illegal', 'no_laws', 'varies'
  marriage_equality       TEXT,             -- 'legal', 'civil_union', 'none'
  adoption_rights         TEXT,             -- 'legal', 'single_only', 'none'
  anti_discrimination     TEXT,             -- 'sexual_orientation', 'gender_identity', 'both', 'none'
  anti_propaganda_law     INTEGER DEFAULT 0 -- 1 if anti-propaganda law exists
    CHECK (anti_propaganda_law IN (0, 1)),
  criminalization         TEXT,             -- 'death_penalty', 'imprisonment', 'fine', 'none'
  gender_marker_change    TEXT,             -- 'legal', 'surgery_required', 'impossible'
  conversion_therapy      TEXT,             -- 'banned', 'legal', 'no_law'
  last_equaldex_update    TEXT,             -- ISO 8601 datetime of last Equaldex sync
  equaldex_region_id      TEXT,             -- Equaldex internal ID for change tracking
  created_at              TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_legal_status_destination ON legal_status(destination_id);

-- ============================================================
-- safety_alerts
-- Generated by monitoring agents. All start human_reviewed = 0.
-- published_at is set by human reviewer on approval.
-- ============================================================
CREATE TABLE IF NOT EXISTS safety_alerts (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  destination_id  TEXT NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  severity        TEXT NOT NULL
    CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  agent_type      TEXT NOT NULL
    CHECK (agent_type IN ('legal', 'news', 'event', 'community', 'social')),
  source_url      TEXT,                     -- canonical URL of the triggering source
  source_name     TEXT,                     -- human-readable source name
  summary         TEXT NOT NULL,            -- plain-language description of the alert
  previous_value  TEXT,                     -- what was true before (for legal changes)
  new_value       TEXT,                     -- what is true now (for legal changes)
  human_reviewed  INTEGER NOT NULL DEFAULT 0
    CHECK (human_reviewed IN (0, 1)),
  reviewer_notes  TEXT,                     -- internal notes from human reviewer (never published)
  published_at    TEXT,                     -- null until human approved; ISO 8601 when published
  expires_at      TEXT,                     -- optional: when this alert should auto-expire
  raw_payload     TEXT,                     -- JSON: full source API response for audit trail
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_alerts_destination ON safety_alerts(destination_id);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON safety_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_reviewed ON safety_alerts(human_reviewed);
CREATE INDEX IF NOT EXISTS idx_alerts_published ON safety_alerts(published_at);
CREATE INDEX IF NOT EXISTS idx_alerts_agent ON safety_alerts(agent_type);

-- ============================================================
-- community_reports
-- Submitted by travelers via Tally form.
-- Processed by community-validator agent.
-- approved = 0 until human reviewer signs off.
-- PII is stripped before insert — submitter contact info
-- is used only for follow-up on critical reports and is
-- never stored here.
-- ============================================================
CREATE TABLE IF NOT EXISTS community_reports (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  destination_id  TEXT NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  visit_date      TEXT,                     -- approximate date of travel (YYYY-MM or YYYY-MM-DD)
  audience_tags   TEXT,                     -- JSON array: ['gay_men','trans','solo_traveler', ...]
  incident_type   TEXT NOT NULL
    CHECK (incident_type IN (
      'none',
      'verbal_harassment',
      'physical_threat',
      'physical_assault',
      'police_interaction',
      'property_crime',
      'discrimination',
      'positive_experience',
      'other'
    )),
  incident_detail TEXT,                     -- free-text description (anonymized)
  neighborhood    TEXT,                     -- general area within city (never specific address)
  validity_score  REAL,                     -- 0.0–1.0 assigned by community-validator agent
  validity_notes  TEXT,                     -- agent's reasoning for validity score
  approved        INTEGER NOT NULL DEFAULT 0
    CHECK (approved IN (0, 1)),
  reviewer_notes  TEXT,                     -- internal notes from human reviewer
  published_at    TEXT,                     -- null until approved
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_reports_destination ON community_reports(destination_id);
CREATE INDEX IF NOT EXISTS idx_reports_approved ON community_reports(approved);
CREATE INDEX IF NOT EXISTS idx_reports_incident ON community_reports(incident_type);

-- ============================================================
-- subscribers
-- Alert subscribers. Stores preferences for destination-specific
-- or tier-based alerts. Email is stored hashed for lookup;
-- plaintext email is never stored after the welcome email is sent.
--
-- alert_tier: 'all' = every alert; 'high' = high+critical only;
--             'critical' = critical only
-- ============================================================
CREATE TABLE IF NOT EXISTS subscribers (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  email_hash       TEXT NOT NULL UNIQUE,    -- SHA-256 of lowercase email — for dedup only
  destination_tags TEXT,                    -- JSON array of destination IDs to monitor
  alert_tier       TEXT NOT NULL DEFAULT 'high'
    CHECK (alert_tier IN ('all', 'high', 'critical')),
  buttondown_id    TEXT,                    -- Buttondown subscriber ID for email delivery
  created_at       TEXT NOT NULL DEFAULT (datetime('now')),
  last_active      TEXT
);

CREATE INDEX IF NOT EXISTS idx_subscribers_tier ON subscribers(alert_tier);

-- ============================================================
-- agent_runs
-- Audit log of every agent execution. Used for debugging,
-- monitoring agent health, and proving to funders that the
-- pipeline runs as described.
-- ============================================================
CREATE TABLE IF NOT EXISTS agent_runs (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  agent_type    TEXT NOT NULL,
  started_at    TEXT NOT NULL DEFAULT (datetime('now')),
  finished_at   TEXT,
  status        TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'success', 'error')),
  alerts_created INTEGER DEFAULT 0,
  error_message  TEXT,
  metadata       TEXT                       -- JSON: agent-specific run metadata
);

CREATE INDEX IF NOT EXISTS idx_runs_agent ON agent_runs(agent_type);
CREATE INDEX IF NOT EXISTS idx_runs_status ON agent_runs(status);
